### ISSUE TITLE
Guardian TODO

### ISSUE THREAD

**Issue by Yahnich** [Yahnich/raid-kings#37]
Innate and Signature
- [ ] Signature: Great Cleave
- [ ] Innate: Fortitude

Skills

- [ ] Skill 1: Anchor Howl
- [ ] Skill 2: Glorious Shield
- [ ] Skill 3: Shield Bash
- [ ] Skill 4: Punish
- [ ] Skill 5: Challenge
- [ ] Skill 6: Rallying Cry
- [ ] Skill 7: Guardian's Spirit
- [ ] Skill 8: Stone Fortress
